import { HubSignaturePoint, HubSignatureStroke } from '../models/signature.types';

/**
 * Reads the intentionally small SVG dialect emitted by `serializeHubSignature`.
 * Rejecting unsupported commands makes form restoration deterministic and avoids
 * treating arbitrary SVG markup as executable document content.
 *
 * @param svg - Form value previously emitted by this library.
 * @returns Captured strokes or an empty drawing for invalid values.
 */
export function parseHubSignature(svg: string): HubSignatureStroke[] {
	const paths = svg.match(/<path\b[^>]*>/g) ?? [];
	return paths.flatMap((path) => {
		const d = readAttribute(path, 'd');
		const color = readAttribute(path, 'stroke');
		const width = Number(readAttribute(path, 'stroke-width'));
		const points = d ? parsePoints(d) : [];

		return color && Number.isFinite(width) && width > 0 && points.length ? [{ points, color, width }] : [];
	});
}

/** Reads a quoted XML attribute without interpreting embedded markup. */
function readAttribute(source: string, name: string): string | null {
	return new RegExp(`${name}="([^"]*)"`).exec(source)?.[1] ?? null;
}

/** Parses the move/line commands generated by the serializer. */
function parsePoints(d: string): HubSignaturePoint[] {
	const commands = [...d.matchAll(/[ML]\s*(-?(?:\d+\.?\d*|\.\d+))\s+(-?(?:\d+\.?\d*|\.\d+))/g)];
	return commands.map(
		(command) => ({ x: Number(command[1]), y: Number(command[2]), pressure: 0.5 }) satisfies HubSignaturePoint
	);
}
